version: "3.9"
services:
  redis:
    container_name: redis-ticket-server
    image: redis:7-bookworm
    ports:
      - "6379:6379"
    networks:
      - ticket-network
    restart: always
    volumes:
      - ./redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --loglevel notice --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

  server:
    container_name: ticket-server
    image: ticket-server:1.0.0
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - ticket-network
    restart: always
    depends_on:
      - redis
    command:
      ["python", "server.py", "-h", "0.0.0.0", "-p", "8080", "-d", "True"]

  client:
    container_name: ticket-client
    image: ticket-client:1.0.0
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "86:6000"
    networks:
      - ticket-network
    restart: always
    tty: true
    stdin_open: true

networks:
  ticket-network:
    external: true
