version: '3.3'
services:
  server:
    container_name: ticket-server
    image: ticket-server:latest
    ports:
      - "85:5000"
    environment:
      - PORT=5000
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_PORT=3306
      - DATABASE_URL=mysql
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /tmp/slack_bot/mysqld:/run/mysqld
    networks:
      - red
    restart: always

  client:
    container_name: ticket-client
    image: ticket-client:latest
    ports:
      - "86:6000"
    networks:
      - red
    restart: always

networks:
  red: